# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-01 00:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camaras',
            fields=[
                ('ID_Camara', models.AutoField(primary_key=True, serialize=False)),
                ('Puerto', models.CharField(default='0000', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('ID_Departamento', models.AutoField(primary_key=True, serialize=False)),
                ('Departamento', models.CharField(choices=[('Produccion', 'Produccion'), ('Finanzas', 'Finanzas'), ('Gerencia', 'Gerencia'), ('Sisetemas', 'Sistemas'), ('Enfermeria', 'Enfermeria'), ('Administrativo', 'Administrativo'), ('Recursos Humanos', 'Recuros Humanos')], max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('ID_Usuario', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('ApellidoP', models.CharField(max_length=50)),
                ('ApellidoM', models.CharField(max_length=50)),
                ('TipoUsuario', models.CharField(choices=[('Administrador', 'Administrador'), ('Gerente General', 'Gerente General'), ('Gerente', 'Gerente'), ('Supervisor', 'Supervisor'), ('Empleado', 'Empleado'), ('Outsourcing', 'Outsourcing'), ('Practicante', 'Practicante')], max_length=15)),
                ('RFC', models.CharField(max_length=13)),
                ('Domicilio', models.CharField(max_length=100)),
                ('Celular', models.IntegerField()),
                ('Correo', models.EmailField(max_length=100)),
                ('Sexo', models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino')], max_length=9)),
                ('Departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Video.Departamentos')),
                ('Usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='departamentos',
            name='ID_Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Video.Usuarios'),
        ),
        migrations.AddField(
            model_name='camaras',
            name='ID_Departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Video.Departamentos'),
        ),
        migrations.AddField(
            model_name='camaras',
            name='ID_Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Video.Usuarios'),
        ),
    ]
