# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-02 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamentos',
            name='Departamento',
            field=models.CharField(choices=[('Gerencia', 'Gerencia'), ('Produccion', 'Produccion'), ('Finanzas', 'Finanzas'), ('Enfermeria', 'Enfermeria'), ('Administrativo', 'Administrativo'), ('Recursos Humanos', 'Recuros Humanos'), ('Sisetemas', 'Sistemas')], max_length=16),
        ),
        migrations.AlterField(
            model_name='departamentos',
            name='ID_Usuario',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Video.Usuarios'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='Departamento',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Video.Departamentos'),
        ),
    ]
