# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-02 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Video', '0002_auto_20180602_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamentos',
            name='ID_Usuario',
        ),
        migrations.AlterField(
            model_name='departamentos',
            name='Departamento',
            field=models.CharField(choices=[('Sisetemas', 'Sistemas'), ('Recursos Humanos', 'Recuros Humanos'), ('Gerencia', 'Gerencia'), ('Enfermeria', 'Enfermeria'), ('Produccion', 'Produccion'), ('Finanzas', 'Finanzas'), ('Administrativo', 'Administrativo')], max_length=16),
        ),
    ]
