# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-02 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Video', '0003_auto_20180602_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamentos',
            name='Departamento',
            field=models.CharField(choices=[('Recursos Humanos', 'Recuros Humanos'), ('Sisetemas', 'Sistemas'), ('Enfermeria', 'Enfermeria'), ('Gerencia', 'Gerencia'), ('Produccion', 'Produccion'), ('Finanzas', 'Finanzas'), ('Administrativo', 'Administrativo')], max_length=16),
        ),
    ]
