# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-04 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Video', '0004_auto_20180602_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamentos',
            name='Departamento',
            field=models.CharField(choices=[('Finanzas', 'Finanzas'), ('Gerencia', 'Gerencia'), ('Administrativo', 'Administrativo'), ('Recursos Humanos', 'Recuros Humanos'), ('Enfermeria', 'Enfermeria'), ('Produccion', 'Produccion'), ('Sisetemas', 'Sistemas')], max_length=16),
        ),
    ]
