# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-04 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Video', '0005_auto_20180604_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamentos',
            name='Departamento',
            field=models.CharField(choices=[('Produccion', 'Produccion'), ('Sisetemas', 'Sistemas'), ('Enfermeria', 'Enfermeria'), ('Gerencia', 'Gerencia'), ('Recursos Humanos', 'Recuros Humanos'), ('Administrativo', 'Administrativo'), ('Finanzas', 'Finanzas')], max_length=16),
        ),
    ]
