# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-04 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Video', '0006_auto_20180604_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamentos',
            name='Departamento',
            field=models.CharField(choices=[('Recursos Humanos', 'Recuros Humanos'), ('Enfermeria', 'Enfermeria'), ('Finanzas', 'Finanzas'), ('Sisetemas', 'Sistemas'), ('Administrativo', 'Administrativo'), ('Gerencia', 'Gerencia'), ('Produccion', 'Produccion')], max_length=16),
        ),
    ]
