# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-04 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Video', '0007_auto_20180604_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamentos',
            name='Departamento',
            field=models.CharField(max_length=50),
        ),
    ]
